import type { GuideContent } from '../types';
import { money as m } from '../numbers';
export const debtGuides: GuideContent[] = [
{
slug:'debt-snowball-vs-avalanche',title:'Debt Snowball vs Debt Avalanche',seoTitle:'Debt Snowball vs Debt Avalanche: Worked Comparison',description:'Compare two debt-payment priorities using the same monthly budget, minimum payments and same-month rollover, with a verified three-debt example.',summary:'Separate the order of extra payments from actual payoff dates and interest costs.',intro:'Snowball and avalanche are ways to direct extra debt payments. A fair comparison holds the debts and total monthly payment budget constant, then changes only the priority.',takeaway:'Both methods maintain minimum payments. Snowball prioritizes the smallest starting balance; avalanche prioritizes the highest rate. The monthly budget and whether the plan is followed matter alongside the ordering.',category:'Debt',relatedCalculator:'debt-snowball',calculatorAssociations:['debt-snowball','loan-payoff','budget'],reviewedAt:'2026-09-18',relatedGuides:['loan-prepayments','monthly-budget','apr-vs-apy'],ogHeadline:'Two priorities, one debt budget',ogSubheadline:'Minimums, rollover and the cost of payment order.',fixtureIds:['debt-snowball','debt-avalanche'],
sections:[
{id:'priority',heading:'Two ways to direct extra dollars',body:`The snowball method directs extra money to the smallest balance first while maintaining required payments on the other debts. The avalanche method directs extra money to the highest interest rate first. CFPB’s debt worksheet explains both priorities and the different motivations behind them.

In MoneyBasis, snowball uses initial balance order. Avalanche uses descending rate, then smaller balance to break a rate tie. Remaining ties keep the entered order. The priority is established at the start; it is not a new sorting of remaining balances every month.

This distinction matters because a payoff plan needs a reproducible rule. Otherwise, two schedules described with the same label could assign extra dollars differently. Neither ordering changes the need to meet the other debts’ minimums.`,sources:['debt']},
{id:'shared-budget',heading:'Minimums are part of one shared monthly budget',body:`The monthly debt budget is the total available to all listed debts, not an extra amount added on top of every minimum. MoneyBasis first accrues monthly interest, reserves each active debt’s required minimum capped at its balance plus interest, and then directs the remaining dollars through the selected priority.

If an account is cleared before its allocated dollars are exhausted, the unused amount can go to the next account in the same month. Waiting until the following month would leave some of the stated budget unused and describe a slower plan. The final month spends only what is needed to clear the remaining debt; unused budget is not counted as an extra debt payment.

A budget below the required minimum total is not a feasible version of either method. Raising the priority of one account cannot justify failing to allocate the other accounts’ required payments. The calculator rejects an insufficient budget rather than manufacturing a successful payoff schedule.`},
{id:'example',heading:'Worked example: three debts and $800 per month',body:`Use a credit card with $4,200 at 19.9% and a $120 minimum; a personal loan with $3,500 at 12% and a $110 minimum; and a car loan with $11,000 at 6.5% and a $265 minimum. The fixed minimums total $495, leaving $305 of the $800 budget for priority payments at the start.

Snowball directs that initial extra amount to the personal loan; avalanche directs it to the credit card. Both keep paying the car loan minimum. The rates are fixed annual inputs divided by twelve, with payments following monthly interest. No new charges, fees or missed payments enter either scenario.

Both methods clear these particular debts in 26 months. Snowball incurs ${m('debt.snowballInterest')} of interest; avalanche incurs ${m('debt.avalancheInterest')}. Identical whole-month payoff counts therefore do not imply identical costs. The final partial payments differ.`,exhibits:['debt']},
{id:'payoff-order',heading:'Priority order and payoff order are not synonyms',body:`Priority tells the model where to send extra money. Actual chronological payoff order records when each balance reaches zero after all payments. A lower-priority debt can clear early through its own minimum payments. It is therefore possible for a payoff timeline to differ from the initial extra-payment list.

The following tables show both concepts for the worked example, along with the first month’s allocation. The debt identities remain separate even if two accounts have the same display name. MoneyBasis tracks distinct account IDs so that clearing one account does not erase another account with a matching label.

A statement’s minimum may change as the balance changes. The example instead holds each entered minimum fixed, apart from capping the final amount due. That is part of the planning model and needs to be revisited when comparing its schedule with a real account.`,exhibits:['debt-snowball','debt-avalanche']},
{id:'cost-and-behavior',heading:'Interest cost and follow-through are different considerations',body:`Directing extra money toward a higher rate reduces exposure to that rate sooner. In this fixed-rate, fixed-budget example, avalanche has the lower interest total. That arithmetic does not establish which plan a particular person will maintain through changing income, competing bills or motivation.

Snowball emphasizes closing smaller balances, which can make progress visible sooner in some debt lists. It does not guarantee the first account will close faster in every possible comparison, and a psychological benefit cannot be measured by the interest engine. The behavioral question is separate from the modeled cost difference.

Comparing methods with different payment budgets obscures the ordering effect. A larger monthly payment can matter more than a modest difference in priority. A useful comparison holds the shared budget fixed first, then separately explores what a sustainable change in that budget would do.`},
{id:'limits',heading:'Know when the schedule stops describing the debt',body:`The engine assumes fixed rates, no new borrowing, no fees and regular monthly payments. It does not model promotional expiration, daily credit-card interest, variable rates, delinquency rules, settlements or lender-specific allocation across multiple balances on one account.

A payment that fails to cover interest can leave a balance growing. The result must not be read as a completed payoff merely because a simulation stopped. MoneyBasis limits this multi-debt simulation to 600 months and distinguishes payoff from a plan that remains unpaid at the horizon.

Payoff dates are estimates in calendar months under the entered schedule. They are not creditor payoff quotes. The useful output is the relationship among payment budget, priority, accrued interest and remaining balances under one explicit set of assumptions.`},
],exercise:'Enter the three balances, rates and minimums from the example with an $800 total monthly budget. Switch only the method. Compare first-month payments, each account’s payoff month and total interest. Then change the budget separately to distinguish the effect of paying more from the effect of changing priority.',
},
{
slug:'loan-prepayments',title:'Extra Loan Payments: How Principal, Interest and Payoff Change',seoTitle:'Extra Loan Payments: Principal, Interest and Payoff',description:'Compare $300 and $400 monthly payments on a $10,000 loan at 12%, including the first payments, final partial payment and interest saved.',summary:'Follow an extra payment through the balance, later interest and final payoff.',intro:'An extra principal payment changes more than the current balance. It also changes the base on which later interest is calculated, which can shorten the repayment schedule.',takeaway:'Under a fixed-rate monthly model, reducing principal earlier lowers later interest. The final payment is capped at the amount still due; payments at or below accrued interest need a different interpretation.',category:'Debt',relatedCalculator:'loan-payoff',calculatorAssociations:['loan-payoff','debt-snowball','mortgage'],reviewedAt:'2026-09-18',relatedGuides:['debt-snowball-vs-avalanche','mortgage-amortization','apr-vs-apy'],ogHeadline:'What an extra $100 changes',ogSubheadline:'A loan balance, two payment paths and a partial final payment.',fixtureIds:['loan-300','loan-400'],
sections:[
{id:'monthly-ledger',heading:'One payment has an interest part and a principal part',body:`In MoneyBasis’s deterministic monthly-interest model, interest equals the opening loan balance multiplied by the annual rate divided by twelve. The payment is then applied. Principal reduction is payment minus that month’s interest, and the closing balance becomes the next month’s opening balance.

This ordering matters. An extra payment made at the modeled month end does not retroactively reduce interest already accrued for that month. It reduces the balance used for later months. The general principal-and-interest distinction is the same one used in mortgage amortization, though real loan contracts can have different timing rules.`,sources:['mortgage']},
{id:'example',heading:'Worked example: $10,000 at 12%, paying $300',body:`At a 12% annual rate divided by twelve, the monthly rate is 1%. First-month interest is $100. A $300 payment therefore reduces principal by $200 and leaves $9,800. Month-two interest is $98, so the next $300 payment reduces principal by $202 and leaves $9,598.

The schedule ends after 41 monthly payments, including a partial final payment. Total interest is ${m('loan.300Interest')}. This calculation retains precision inside the ledger and rounds only for display; a contract using different rounding or payment dates can produce a slightly different statement balance.`,exhibits:['loan-ledger-300']},
{id:'extra-payment',heading:'Add $100 each month and follow the effect',body:`With a $400 payment, first-month interest is still $100 because both scenarios start with the same balance. Principal reduction becomes $300 and the balance falls to $9,700. Second-month interest is $97; principal reduction is $303 and the balance becomes $9,397.

The higher payment clears the loan in 29 months with ${m('loan.400Interest')} of interest. Compared with $300 monthly, that is 12 fewer months and ${m('loan.saved')} less interest under these assumptions. The savings are caused by reducing balances sooner, not by changing the interest rate.

The two curves include zero after each schedule’s payoff. A line ending at zero is evidence that the modeled balance is cleared; a line merely ending at the tool’s maximum horizon is not.`,exhibits:['loan-ledger-400','loan-comparison','loan']},
{id:'partial-and-one-time',heading:'A recurring extra and a one-time extra have different timing',body:`A recurring monthly extra increases the scheduled payment from the first modeled month onward. A one-time extra is added only in the specified month, after that month’s interest. If the debt has already been cleared by then, there is no remaining balance to receive it.

The final payment is capped at remaining principal plus that month’s interest. It is not necessary to pay the full regular amount when less is owed. That cap is why total paid is not always the displayed monthly amount multiplied by the number of months.

An earlier one-time principal payment usually reduces more subsequent interest in this fixed positive-rate model than the same amount paid later, because it affects more opening balances. But the tool does not assess the value of retaining cash for other needs or alternative uses. The schedule is one part of that broader comparison.`},
{id:'non-amortizing',heading:'When a payment does not reduce the balance',body:`For the $10,000 balance at a 1% monthly rate, a $100 payment covers first-month interest exactly. With the same rate and payment continuing, principal does not fall. A payment below $100 fails to cover all interest; if unpaid interest is added to the debt as in this model, the balance grows. That is negative amortization.

A non-amortizing result is not a zero-month payoff or an ordinary payoff date far in the future. It identifies a schedule that does not currently reduce the debt sufficiently under the stated assumptions. An extra payment can change later behavior, which is why the full monthly ledger and actual status matter.

MoneyBasis also has a 1,200-month single-loan simulation horizon. A debt remaining at that boundary is reported as horizon-exceeded, not repaid. This computational limit is distinct from a non-amortizing payment structure.`},
{id:'contract-limits',heading:'Check the contract before treating the illustration as a payoff quote',body:`A real lender may use daily simple interest, different due dates, accrued fees, prepayment conditions or instructions for applying extra money. An amount sent ahead may be treated as an early future installment unless the servicer applies it as intended. The monthly model cannot determine those contract-specific rules.

Recasting a mortgage can change its scheduled payment after a principal reduction, while refinancing creates a new loan. The extra-payment comparison here keeps the existing rate and base monthly payment fixed. It does not price those alternatives or model associated fees.

A modeled payoff month is a planning date. The amount required to close an account on a particular day comes from the lender’s payoff calculation. Keeping that distinction visible allows the two curves to teach the mechanism without promising an exact servicing outcome.`,sources:['housing','recast']},
],exercise:'Enter $10,000 balance, 12% annual rate and a $300 regular monthly payment. Set one-time extra to zero. Compare no monthly extra with $100 monthly extra. Inspect the first two payments and final payment, then try a $100 regular payment to see the interest-only boundary.',
},
];
