import type { GuideContent } from '../types';
import { money as m, percent as pct } from '../numbers';
export const growthGuides: GuideContent[] = [
{
  slug:'compound-interest',title:'Compound Interest: Growth, Contributions and Inflation',seoTitle:'Compound Interest: Growth, Contributions and Inflation',description:'Separate contributions from compound growth, compare rate conventions and translate a future balance into today’s purchasing power.',summary:'Understand what you put in, what the model adds and what future dollars can buy.',intro:'A growing account balance has two possible sources: money added and growth on money already invested. Separating them makes a compounding example much more useful than a single impressive future number.',takeaway:'Contributions are cash you supply; growth depends on the assumed rate and timing. A smooth compound-growth curve describes a scenario, not the path an investment will actually take.',category:'Saving & Investing',relatedCalculator:'compound-interest',calculatorAssociations:['compound-interest','savings-goal','retirement'],reviewedAt:'2026-09-18',relatedGuides:['nominal-vs-real-return','apr-vs-apy','how-much-to-save'],ogHeadline:'What makes an account grow?',ogSubheadline:'Contributions, compound growth and purchasing power.',fixtureIds:['compound-lump','compound-monthly','compound-zero','compound-loss'],
  sections:[
    {id:'principal-and-growth',heading:'Compounding starts with money that remains invested',body:`Principal is the starting money. If interest is retained, later interest can be earned on both principal and accumulated interest. Investor.gov describes this as compound interest. For a market investment, the same mathematical pattern is often used to model reinvested total returns, but the word “interest” does not make those returns contractually fixed.

A recurring contribution is different. It raises the account balance because new cash enters the account. To measure modeled growth, subtract both the starting amount and all later contributions from the final value. Counting new deposits as investment gains overstates what the assumed return produced.

Timing matters because money cannot earn modeled growth before it arrives. A deposit made at the start of a period has one more period to grow than the same deposit made at the end. MoneyBasis uses end-of-month contributions: growth on the opening balance first, then the deposit.`,sources:['compound']},
    {id:'frequency',heading:'The annual rate needs a compounding convention',body:`MoneyBasis’s compound-interest calculator takes a nominal annual rate and a selected compounding frequency: annually, semiannually, quarterly, monthly or daily. If the nominal annual rate as a decimal is a and the selected frequency is k times a year, the effective annual growth factor is (1 + a/k)^k.

Monthly deposits still occur monthly even when another compounding frequency is selected. The model converts the selected frequency into an equivalent monthly growth factor, (1 + a/k)^(k/12). This keeps deposit timing consistent while preserving the chosen effective annual yield. It is a modeling convention, not a statement about when a particular bank credits interest.

A quoted effective annual yield already includes compounding. Entering it as a nominal rate with monthly compounding compounds it again. The APR/APY guide explains the conversion. The frequency control also does not create extra investment return; changing it while holding a nominal input fixed changes the effective yield assumption.`,sources:['apy']},
    {id:'lump-sum',heading:'Example A: a lump sum with annual compounding',body:`Start with $10,000, contribute nothing more and assume a 5% nominal annual rate compounded annually for ten years. The calculation is $10,000 × 1.05^10, producing ${m('compound.lump')}. Contributions remain $10,000; the rest is modeled growth.

There is no evidence about future market performance in that multiplication. The example asks what follows if the rate applies every year. A real investment can have losses, varying returns and costs. The amount is also stated in future nominal dollars, before any adjustment for purchasing power.`},
    {id:'example',heading:'Example B: add $500 at each month end',body:`Now start with $10,000, add $500 each month for twenty years, and use a 7% nominal annual return compounded monthly. The monthly rate is 0.07 ÷ 12. Each deposit has a different time to grow: the first earns growth for 239 subsequent months, and the last earns none before the final measurement.

Total contributed capital is ${m('compound.contributed')}: the initial $10,000 plus 240 deposits of $500. Final modeled value is ${m('compound.total')}, of which ${m('compound.growth')} is growth. The visual keeps these three series separate so the effect of contributions remains visible.

With a constant 3% inflation assumption, divide that final balance by 1.03^20. Its purchasing power is ${m('compound.real')} in today’s dollars. This is another view of the same future balance, not an additional account balance to add to it.`,exhibits:['compound'],sources:['inflation']},
    {id:'zero-and-negative',heading:'Example C: use zero return as a control',body:`With $1,000 initially, $100 contributed at each month end and zero return for one year, the result is $2,200. All of it is contributed capital. That control isolates the saving effort from the assumed growth and is useful when the goal date is fixed.

Negative returns remain negative in MoneyBasis. A $1,000 lump sum with no deposits and a −12% nominal annual return compounded monthly becomes ${m('compound.loss')} after one year. That is a loss; it is not clipped to zero growth. The annual loss differs from exactly 12% because the monthly loss factor is compounded.

Contributions can make an account’s final balance exceed its starting balance even when investment growth is negative. Compare ending value with total contributed capital to distinguish that situation from a positive investment result.`},
    {id:'fees-and-uncertainty',heading:'Costs and an uneven path change the interpretation',body:`Fees remove money that would otherwise remain invested, reducing both the current balance and the base for later growth. MoneyBasis does not apply an expense ratio, advisory fee, transaction fee or tax calculation separately. If the return input is intended to be after some costs, that assumption needs to be stated; a before-cost return and an after-cost return are different scenarios.`,sources:['fees']},
    {id:'using-the-curve',heading:'Read the curve as a controlled experiment',body:`The curve assumes a constant return, the chosen deposit timing and no withdrawals. Optional contribution increases take effect after each completed year. Increasing a contribution is an additional cash commitment, not an improvement in investment performance. Inflation is constant in the purchasing-power comparison, which does not estimate a household’s exact future spending basket.

A smooth curve contains no market shocks, recovery periods or behavioral interruptions. Lower and higher rates can show sensitivity, but they do not create confidence intervals. When deposits or withdrawals occur along the way, different return sequences can also produce different outcomes despite similar average returns. The retirement guide develops that distinction with explicit cash flows.

A practical reading order is contributed capital, assumed growth, then purchasing power. That sequence makes it easier to see which part of a result comes from controllable deposits and which part depends on uncertain inputs.`},
  ],exercise:'Use $10,000 initially, $500 monthly, 7% nominal annual return, monthly compounding, 20 years, 0% contribution increase and 3% inflation. Compare the final value with total contributions and the inflation-adjusted result. Then set return to 0% without changing deposits. Separately reproduce the $1,000 + $100/month one-year control.',
},
{
  slug:'how-much-to-save',title:'How Much to Save Each Month for a Specific Goal',seoTitle:'How Much to Save Monthly for a Specific Goal',description:'Calculate a monthly deposit from a goal, current savings and deadline. Distinguish achieved-today, growth-funded and deposits-required cases.',summary:'Start with the funding gap, then see how time and an assumed return change the deposit.',intro:'A monthly savings estimate is the answer to a specific funding question: how much needs to be added, on what schedule, to reach a stated amount by a stated date?',takeaway:'The required deposit depends on the target, existing balance, time and assumed growth. A zero deposit can mean projected growth covers the gap; it does not necessarily mean the goal is funded today.',category:'Saving & Investing',relatedCalculator:'savings-goal',calculatorAssociations:['savings-goal','compound-interest','budget'],reviewedAt:'2026-09-18',relatedGuides:['monthly-budget','compound-interest','nominal-vs-real-return'],ogHeadline:'Turn a goal into monthly deposits',ogSubheadline:'The funding gap, the deadline and the growth assumption.',fixtureIds:['savings-zero-1','savings-zero-2','savings-zero-3','savings-growth','savings-growth-funded'],
  sections:[
    {id:'define-the-goal',heading:'Name the target and the money assigned to it',body:`A target needs an amount and a deadline. Existing savings means money available for this particular goal, not every balance held elsewhere. The same cash cannot fully fund two separate goals at once. A periodic saving plan connects that remaining gap to a repeatable transfer amount.`,sources:['savings']},
    {id:'example',heading:'Start with a zero-return example',body:`Suppose the target is $12,000 and $3,000 is already assigned to it. The funding gap is $9,000. At zero return, divide that gap by the number of monthly deposits: twelve months requires $750 each month; twenty-four requires $375; thirty-six requires $250.

This is not a required personal savings rule. It is arithmetic for one target. If $750 does not fit the available cash flow, the inputs do not yet describe an affordable plan. Changing the deadline, the target or the money assigned to it changes the required transfer without assuming that markets will provide the missing cash.

MoneyBasis uses monthly periods and deposits at month end. A one-year horizon therefore means twelve deposits. It does not assume a deposit was made before the start. A dated real-world goal may have a different number of paydays or transfer dates, so the monthly approximation needs to be compared with the actual calendar.`,exhibits:['savings-zero']},
    {id:'include-growth',heading:'Then allow existing savings and deposits to grow',body:`With an assumed return, the first step is to find the future value of money already saved. The second is to determine the portion of the target still unfunded at the deadline. The recurring deposit fills that future gap, taking account of how long each new deposit remains invested.

For an illustrative $50,000 goal, $5,000 already saved, four years and a 4% nominal annual return divided by twelve, the unrounded solution displays as ${m('savings.deposit')} per month. Over forty-eight deposits, new contributions total ${m('savings.new')}; modeled growth is ${m('savings.growth')}. Together with the initial $5,000 they reach the $50,000 goal.

The visual uses the unrounded solved deposit, as does the engine. An actual recurring transfer rounded to cents can finish slightly above or below the displayed target. Fees, taxes and a different timing of transfers can change the result more substantially.`,exhibits:['savings']},
    {id:'three-states',heading:'Achieved today, growth-funded, or deposits required',body:`Achieved today describes the current balance: existing savings already equal or exceed the stated target. It does not mean that balance can never fall, nor that a future purchase price will remain unchanged.

Growth-funded describes a different case: the balance is below target today, but its modeled future value reaches the target with no additional deposits. For example, $9,000 with a deliberately illustrative 12% nominal annual return compounded monthly becomes ${m('savings.growthFunded')} after a year, exceeding a $10,000 target. The monthly deposit is zero under that assumption, yet the goal is not funded today. This high return is a teaching input, not a suggested planning expectation.

Deposits required means the projected existing balance leaves a gap. A negative assumed return can increase that gap and produce negative accumulated growth. It can even require future deposits when the target is already achieved today, because current funding status and projected funding at the deadline answer different questions. MoneyBasis preserves these distinctions rather than labeling every zero-deposit result “already there.”`},
    {id:'nominal-target',heading:'The target is a future nominal dollar amount',body:`MoneyBasis does not automatically inflate a savings goal. Entering $12,000 asks for $12,000 at the chosen deadline, even if the return assumption is positive. Return is growth of the savings; inflation is growth in the cost of what those savings need to buy.

If the goal is expressed as today’s purchasing power, first create an explicitly inflation-adjusted future target. For example, $10,000 of today’s purchasing power at a constant 3% inflation assumption becomes ${m('real.target')} after ten years. Enter that future nominal amount as the goal if those are the intended assumptions. Do not also deflate or inflate the same target a second time.

A specific purchase price can change differently from broad inflation. The future-target conversion is a scenario, not a price quote. Shorter deadlines also leave less time to recover from a loss, which a constant-rate projection does not represent.`,sources:['inflation']},
    {id:'affordability',heading:'Reconcile the deposit with the budget',body:`A solved deposit is only one side of the plan. The monthly budget shows the income and outflows available to fund it. If a savings transfer is already included among budget outflows, counting it again against remaining cash would double-count the commitment.

The goal calculator assumes deposits continue at the solved level and the selected return applies. It does not verify account eligibility, guarantee an investment outcome, choose a product or reserve funds in an account. Comparing a zero-return case with the growth case makes the reliance on future growth visible. Revisiting actual balances and remaining time later can reveal whether the same inputs still describe the goal.`},
  ],exercise:'First enter a $12,000 goal, $3,000 saved, 0% return and one year; change only the time to two and three years. Then try $50,000, $5,000 saved, 4% nominal return and four years. Compare the solved deposit with the amount explicitly available in your budget.',
},
{
  slug:'nominal-vs-real-return',title:'Nominal vs Real Return: What Future Dollars Can Buy',seoTitle:'Nominal vs Real Return and Purchasing Power',description:'Translate future nominal balances into today’s dollars and understand the exact real-return relationship, inflation assumptions and savings targets.',summary:'A larger dollar balance does not always mean more purchasing power.',intro:'Nominal value counts dollars. Real value asks what those dollars can buy after allowing for changes in prices. Keeping the two units separate matters whenever money and spending sit at different dates.',takeaway:'Divide a future nominal amount by the accumulated inflation factor to express it in today’s dollars. For one matching period, exact real return is (1 + nominal return) ÷ (1 + inflation) − 1.',category:'Saving & Investing',relatedCalculator:'compound-interest',calculatorAssociations:['compound-interest','retirement','savings-goal'],reviewedAt:'2026-09-18',relatedGuides:['compound-interest','four-percent-rule','how-much-to-save'],ogHeadline:'Future dollars, today’s buying power',ogSubheadline:'Nominal value and real value tell different stories.',fixtureIds:['nominal-real'],
  sections:[
    {id:'two-units',heading:'Treat the dollar date as a unit',body:`A future nominal balance is the number of dollars at that future date. A today-dollar balance expresses its purchasing power relative to today’s price level. The two can describe the same account, just as two units can describe the same physical distance.

BLS explains constant-dollar conversions using price-index ratios. MoneyBasis uses a simpler planning assumption: one selected inflation rate repeated over the horizon. For a future amount F, annual inflation i and t years, today-dollar value is F ÷ (1 + i)^t. This does not predict the path of an actual price index.

Calling an amount “real” also does not make it after-tax or freely spendable. Taxes, withdrawal restrictions and transaction costs are separate considerations. The label means inflation-adjusted only unless additional adjustments are explicitly named.`,sources:['inflation']},
    {id:'exact-rate',heading:'Why subtracting inflation is only an approximation',body:`If an investment grows by an effective 7% over a year while prices rise 3%, the purchasing-power growth factor is 1.07 ÷ 1.03. Subtract one to get a real return of ${pct('real.rate')}. Subtracting 3% from 7% gives a nearby 4%, but not the exact result.

The exact relationship uses growth factors because the investment value and the price of goods both change. Dividing those factors compares how many units of goods can be bought afterward. The simple subtraction r − i is a convenient approximation when rates are small; it is not an identity.

Both rates must refer to the same period. The nominal return in this relationship is the effective return over that period, not necessarily the nominal annual rate entered into a compounding calculator. A nominal rate compounded monthly must first be converted to its effective annual factor before being compared with annual inflation.`,sources:['apy']},
    {id:'example',heading:'Worked example: one account, two views',body:`Start with $10,000 and no further deposits. Assume 7% growth compounded annually for ten years and constant annual inflation of 3%. The nominal future value is ${m('real.nominal')}. Divide by 1.03^10 and the same balance is ${m('real.value')} in today’s purchasing power.

Both lines begin at $10,000 because today’s dollars and nominal dollars coincide at the starting date. They separate as the assumed price level rises. The gap does not represent cash removed by a bank; it reflects the change in what each dollar buys.

The nominal balance can rise even when purchasing power falls. That happens when the effective investment growth factor is smaller than the inflation factor. A nominal gain alone therefore cannot establish that a future spending goal has become easier to fund.`,exhibits:['real']},
    {id:'future-spending',heading:'Put the goal and the balance on the same basis',body:`A target expressed in today’s prices needs to be moved forward before comparison with a future nominal account balance. Under 3% constant inflation, $10,000 today becomes ${m('real.target')} after ten years. Alternatively, the future account balance can be brought back to today’s dollars. Either method works when applied consistently.

MoneyBasis’s retirement calculator takes desired monthly spending in today’s dollars, inflates it to retirement, and then increases nominal spending annually during retirement. Its future portfolio balance remains nominal. Comparing that future balance directly with today’s spending without the conversion would understate the future dollar requirement when assumed inflation is positive.

The savings-goal calculator takes a nominal future target. It does not perform this inflation adjustment automatically. The compound-interest calculator can show both nominal future value and an inflation-adjusted value when an inflation assumption is entered. These different interfaces can be consistent because each names the basis it uses.`},
    {id:'limits',heading:'One inflation rate cannot describe every household',body:`An inflation index summarizes a basket, while a household’s spending mix may put more weight on housing, health care, travel or another category. A specific goal can also have a price that changes differently from the general price level. The conversion is only as relevant as the assumed rate and spending definition.

The illustration uses constant rates and has no deposits, taxes or fees. Actual investment returns and inflation vary over time. A one-period real-return formula remains valid for matching measured periods, but a long-term scenario using one constant rate does not show that variation.

Useful labels name both the date and the basis: “future nominal balance” or “today-dollar purchasing power.” Avoid adding those two versions together or treating the inflation-adjusted number as a second asset.`},
  ],exercise:'In Compound Interest enter $10,000, no monthly contribution, 7%, annual compounding, ten years and 3% inflation. Compare the nominal and inflation-adjusted figures. Then change only inflation to see why spending assumptions can change while the nominal account projection remains the same.',
},
{
  slug:'apr-vs-apy',title:'APR vs APY vs Investment Return',seoTitle:'APR vs APY vs Investment Return: Rate Conventions',description:'Learn how borrowing APR, mortgage note rates, deposit APY and nominal investment rates differ, with independently checked conversions.',summary:'Match the rate definition to the calculator field before entering a percentage.',intro:'The same percentage can describe a borrowing cost, a deposit yield or an uncertain investment assumption. The label and compounding convention determine what calculation it belongs in.',takeaway:'A mortgage note rate, disclosure APR, APY and assumed investment return are not interchangeable. First identify what is included in the quoted rate, then match its time and compounding basis to the field.',category:'Saving & Investing',relatedCalculator:'compound-interest',calculatorAssociations:['compound-interest','mortgage','loan-payoff'],reviewedAt:'2026-09-18',relatedGuides:['compound-interest','mortgage-amortization','loan-prepayments'],ogHeadline:'One percentage, different meanings',ogSubheadline:'APR, APY, note rates and investment assumptions.',fixtureIds:['apy-annual','apy-monthly-equivalent','loan-300'],
  sections:[
    {id:'borrowing',heading:'Borrowing: distinguish the note rate from APR',body:`The mortgage note interest rate is used to calculate interest on the outstanding loan. Mortgage APR expresses a broader annualized cost that includes specified fees and charges. CFPB explains that APR can therefore differ from the stated interest rate even for the same loan.

MoneyBasis’s mortgage calculator needs the note rate to amortize principal and interest. It does not calculate a regulatory APR from an origination-fee schedule. Entering an APR that includes fees into the note-rate field can overstate the periodic interest being charged on the balance.

The Loan Payoff and Debt Snowball tools use an APR-style monthly planning convention: the entered annual percentage divided by twelve. This is a simplified borrowing-rate input, not a full reconstruction of all credit disclosures, daily balances or fees. Real contracts may accrue interest daily, have promotional periods or use other rules.`,sources:['apr']},
    {id:'deposit-yield',heading:'APY already includes compounding',body:`Annual percentage yield expresses a deposit account’s annual interest yield with compounding reflected in it. Regulation DD defines it using the interest rate, compounding frequency and specified annual calculation rules. For a fixed rate with interest retained, it answers a different question from simply multiplying a periodic rate by the number of periods.

For a nominal annual rate a compounded k times per year, the effective annual yield is (1 + a/k)^k − 1. A 12% nominal annual rate compounded monthly has a 1% monthly rate and an effective annual yield of ${pct('apy.effective12')}.

A quoted 5% APY therefore is not generally the same as a 5% nominal rate compounded monthly. The latter includes additional compounding on top of the nominal rate. Actual account disclosures also matter when rates vary, balances have tiers or fees apply.`,sources:['apy']},
    {id:'example',heading:'Worked examples: translate rates without changing the question',body:`In a loan example with $10,000 outstanding and a 12% annual input divided by twelve, first-month interest is $100. If a $300 payment follows, $200 reduces principal and the closing balance is $9,800. The interest calculation concerns a debt balance and payment, not an investment yield.

For a deposit comparison, $10,000 earning a fixed 5% APY for a full year with no withdrawals would reach $10,500 before any separate fees or taxes. In MoneyBasis’s compound calculator, 5% with annual compounding reproduces that full-year growth. To use monthly compounding with the same effective annual yield, the nominal annual input is 12 × (1.05^(1/12) − 1), expressed as a percentage: approximately ${pct('apy.nominal5',6)}.

The table places equivalent and nonequivalent rates side by side. These conversions say nothing about the likelihood that a market investment will earn a specified return.`,exhibits:['apy']},
    {id:'investment-return',heading:'An investment input is a scenario assumption',body:`MoneyBasis’s compound-interest field takes a nominal annual investment rate paired with a frequency. Its monthly-equivalent growth factor is derived from those two inputs. A historical annualized total return quoted elsewhere may instead be an effective geometric return over a particular period. Copying it into a nominal monthly-compounding field changes the effective annual assumption.

Market total return can include changes in price and distributions. It is not the same as a deposit contract’s yield, and it need not remain positive. Reinvestment, fees and taxes affect the amount available to grow. The calculator does not separately deduct those costs or recreate the volatility of the underlying asset.

A rate can also be before or after inflation. Compounding frequency and purchasing-power adjustment answer separate questions. An effective annual return can still be nominal in the sense of not inflation-adjusted; “nominal” has both a rate-convention meaning and a dollar-basis meaning, so the surrounding description matters.`,sources:['fees']},
    {id:'field-check',heading:'A short check before copying a rate',body:`Identify the object first: a debt balance, a deposit account or a market investment. Next identify whether the percentage includes fees or compounding. Finally identify its period and whether it is before or after inflation, taxes and investment costs.

Use a note rate for mortgage interest. Use the documented annual-rate-divided-by-twelve convention for simplified payoff schedules, with its contract limitations understood. For Compound Interest, pair the input with the intended frequency or convert an effective yield to its nominal equivalent.

The rate conversion table assumes fixed rates, retained interest and no withdrawals or fees. It is not an offer, a product comparison or a recommended return. An accurate conversion preserves a specified growth assumption; it cannot make uncertain growth certain.`},
  ],exercise:'Enter $10,000, no monthly deposits, one year and 5% with annual compounding; the result is $10,500. Switch to monthly compounding while leaving 5% unchanged and notice that the result changes. Then enter the monthly-equivalent nominal rate shown above to recover approximately the same annual result; rounding the rate can introduce a small difference.',
},
];
