import type { GuideContent } from '../types';
import { money as m } from '../numbers';
export const incomeGuides: GuideContent[] = [
{
slug:'salary-vs-hourly',title:'Salary to Hourly: Gross Pay, Paid Weeks and Tax Estimates',seoTitle:'Salary to Hourly: Gross Pay and Tax Estimates',description:'Convert salary and hourly pay with explicit hours and paid weeks, then understand the limits of a one-worker federal and FICA tax estimate.',summary:'Separate gross-pay arithmetic from an annual federal tax estimate.',intro:'Converting salary to an hourly equivalent is straightforward once hours and paid weeks are defined. Estimating take-home pay is a separate calculation with its own tax year, deductions and limitations.',takeaway:'Annual salary ÷ paid weeks ÷ hours per week gives a gross hourly equivalent. MoneyBasis’s net estimate subtracts modeled federal income tax, employee FICA and entered qualifying deductions; it is not a payroll withholding calculation.',category:'Income & Budgeting',relatedCalculator:'salary-hourly',calculatorAssociations:['salary-hourly','budget'],reviewedAt:'2026-09-18',relatedGuides:['gross-vs-net-pay','monthly-budget','savings-rate-vs-cash-flow'],ogHeadline:'What does a salary mean per hour?',ogSubheadline:'Paid weeks, pay periods and a federal tax estimate.',fixtureIds:['salary-hourly','salary-2026','salary-deductions','salary-medicare'],
sections:[
{id:'gross-conversion',heading:'Define the hours and paid weeks first',body:`Gross pay is compensation before deductions. To convert an annual salary to an hourly equivalent, divide it by hours per week multiplied by paid weeks per year. To annualize hourly pay, multiply the hourly rate by those same two quantities.

The word “paid” matters. A regular schedule, unpaid time away and paid leave can produce different annual totals. The calculator does not determine overtime eligibility or turn a salary into an hourly employment contract. Bonuses, variable schedules, benefits and unpaid work can also make two jobs with the same arithmetic hourly equivalent different offers.

For a fixed annual salary, reducing the entered paid weeks raises the hourly equivalent because the same annual amount is divided across fewer hours. For a fixed hourly rate, reducing paid weeks lowers annualized earnings. Those are different experiments; changing the mode changes which number is held constant.`},
{id:'example',heading:'Worked gross-pay example: $30 an hour',body:`At $30 per hour, 40 hours per paid week and 52 paid weeks, annual gross pay is $62,400. Dividing by twelve gives a $5,200 monthly average; dividing by twenty-six gives $2,400 biweekly; dividing by fifty-two gives $1,200 per paid week.

Biweekly means every two weeks in this annualized convention. Semimonthly means twice a month: twenty-four payments per year, or $2,600 here. The calculator’s biweekly result uses twenty-six; it is not a semimonthly paycheck. The semimonthly row below is a separate arithmetic comparison.

A monthly average is useful for comparing annual income with annualized expenses, but it is not the cash received in every calendar month. The weekly display uses the entered number of paid weeks. When that differs from fifty-two, weekly and calendar-average figures need not share the same denominator.`,exhibits:['pay-periods']},
{id:'tax-layers',heading:'Gross wages, taxable income and tax are different layers',body:`Federal taxable income starts from modeled wages after entered qualifying pretax deductions, then subtracts the selected year’s standard deduction, with a floor at zero. The standard deduction is not cash withheld from a paycheck: it reduces the amount to which income-tax brackets apply.

A marginal tax rate applies to the next dollar within a particular bracket. It does not apply to every dollar of gross pay. An effective income-tax rate divides the calculated income tax by a named income measure, such as gross wages. Including FICA in the numerator would describe a different combined-tax rate, so a label needs to state which taxes it counts.

The following dated example isolates the numerical tax assumptions. The gross-pay conversion above remains useful independently of a tax year.`},
{id:'tax-2026',heading:'2026 example: one worker, single, $75,000 gross',tone:'year-specific',body:`Assume ordinary annual wages of $75,000, single filing status, the base standard deduction, and no pretax deductions, credits or other income. The 2026 standard deduction is $16,100, leaving ${m('salary.taxableIncome')} of federal taxable income.

The bracket slices are $12,400 at 10%, the next $38,000 at 12%, and the remaining $8,500 at 22%. Federal income tax totals ${m('salary.federalTax')}. The marginal rate in this example is 22%; federal income tax divided by gross wages is about 10.23%, not 22% of all wages.

Employee Social Security is 6.2% of covered wages up to the 2026 wage base of $184,500. Employee Medicare is 1.45% without that wage cap. Here Social Security is ${m('salary.socialSecurity')} and Medicare is ${m('salary.medicare')}, leaving a modeled annual net of ${m('salary.netAnnual')}. State and local taxes and other payroll deductions are excluded.`,sources:['irs2026','ssa','cafeteria'],exhibits:['salary']},
{id:'deductions-2026',heading:'2026 deduction and Additional Medicare examples',tone:'year-specific',body:`For the same $75,000 worker, enter $10,000 of traditional 401(k) deferrals and $2,000 of qualifying health-benefit deductions. The model reduces federal wages by both amounts, but FICA wages only by the qualifying health amount. Federal taxable income becomes ${m('deductions.taxableIncome')}; federal tax is ${m('deductions.federalTax')}, Social Security ${m('deductions.socialSecurity')}, and Medicare ${m('deductions.medicare')}. After the $12,000 of deductions, modeled net is ${m('deductions.netAnnual')}.

Traditional employee retirement deferrals generally remain subject to Social Security and Medicare taxes. MoneyBasis assumes health and other pretax inputs qualify for cafeteria-plan treatment that excludes them from federal and FICA wages. Actual benefit eligibility matters; not every deduction receives that treatment. The calculator does not validate plan eligibility or contribution limits.

Additional Medicare tax is 0.9% above the applicable wage threshold: $200,000 for single and head-of-household filers, and $250,000 for married filing jointly. At $300,000 of single-worker Medicare wages, regular Medicare is $4,350 and the additional amount is $900, totaling $5,250. Employer withholding begins above $200,000 of that employee’s wages regardless of filing status, so withholding and final liability can differ.`,sources:['retirementTax','cafeteria','medicare']},
{id:'scope',heading:'What this estimate does and does not represent',body:`MoneyBasis models one worker’s annual federal ordinary-wage income tax and employee FICA for a supported selected year, using the base standard deduction. Selecting married filing jointly does not add spouse wages or apply a separate Social Security cap to a second worker.

It is not W-4 withholding software or a complete tax return. It excludes state and local taxes, credits, itemized deductions, additional age or blindness adjustments, self-employment treatment, and special tips or overtime deductions. It also does not model every benefit, bonus withholding practice or payroll schedule.

Withholding is money paid toward tax during the year; liability is the tax calculated under the applicable rules. A refund or balance due depends on their relationship and on information beyond this model. For a monthly budget, actual take-home receipts can therefore be a more direct cash-flow input than dividing this simplified annual estimate by twelve.`},
],exercise:'For the gross example, choose hourly mode, $30, 40 hours and 52 paid weeks. For the separate tax example, choose salary mode, $75,000, single and 2026 with deductions at zero. Then add $10,000 traditional 401(k) and $2,000 qualifying health deductions and inspect the tax layers rather than only the net headline.',
},
{
slug:'gross-vs-net-pay',title:'Gross Pay vs Net Pay: Taxes, Benefits and Deductions',seoTitle:'Gross Pay vs Net Pay: Taxes and Deductions',description:'Follow gross wages through taxable income, FICA, pretax benefits and a net-pay estimate, with a clearly dated 2026 example.',summary:'Understand why a tax deduction, a retirement transfer and take-home cash are different.',intro:'Gross pay is the starting amount, but several different routes lead from it to spendable cash. Some deductions reduce taxable wages; some move money into your own retirement account; taxes are another category entirely.',takeaway:'Net pay is not simply gross pay times one tax percentage. Federal taxable income, FICA wages, cash deductions and actual withholding need to be distinguished.',category:'Income & Budgeting',relatedCalculator:'salary-hourly',calculatorAssociations:['salary-hourly','budget','retirement'],reviewedAt:'2026-09-18',relatedGuides:['salary-vs-hourly','monthly-budget','savings-rate-vs-cash-flow'],ogHeadline:'Follow gross pay to take-home cash',ogSubheadline:'Taxes, benefits and retirement deductions explained.',fixtureIds:['salary-deductions','salary-2026'],
sections:[
{id:'pay-layers',heading:'Several pay figures can all be correct',body:`Gross wages describe compensation before employee deductions. Federal income-tax wages can be lower when qualifying pretax amounts are excluded. Social Security and Medicare wages can differ from federal wages because exclusions are not identical. Federal taxable income is another step: the annual estimate subtracts the standard deduction from modeled federal wages.

Actual net pay is cash left after payroll taxes, withholding and deductions. MoneyBasis estimates a narrower annual net amount using annual federal income-tax liability, employee FICA and the qualifying deductions entered. It does not claim that this is the amount a payroll system will deposit.

A standard deduction is not a payment to anyone and is not subtracted from cash twice. It changes the income-tax calculation. A retirement contribution, by contrast, is a real transfer out of current spendable pay, even when it remains part of the worker’s assets.`},
{id:'pretax',heading:'Pretax for one tax does not mean exempt from every tax',body:`Traditional employee 401(k) deferrals generally reduce federal income-tax wages but remain subject to employee Social Security and Medicare. Roth deferrals have different federal income-tax treatment and cannot be represented as traditional pretax deferrals in this model.

Qualifying cafeteria-plan benefits may receive exclusions under rules that depend on the benefit and the worker’s eligibility. MoneyBasis treats the health and other pretax inputs as qualifying exclusions from both federal and FICA wages. That assumption is narrower than saying all health costs or all payroll deductions are tax-free.

The calculator does not determine whether a particular plan qualifies, enforce contribution limits or choose between benefit options. Its deduction fields answer a conditional question: what happens to the estimate if these entered amounts receive the stated treatment?`,sources:['retirementTax','cafeteria']},
{id:'example',heading:'2026 worked example: allocate $75,000 of gross pay',tone:'year-specific',body:`Assume one worker, single filing status, $75,000 of annual ordinary wages, a $10,000 traditional 401(k) deferral and a $2,000 qualifying health-benefit deduction. Federal wages are $63,000. After the 2026 base standard deduction of $16,100, federal taxable income is ${m('deductions.taxableIncome')}.

Applying the 2026 brackets yields ${m('deductions.federalTax')} of federal income tax. FICA wages are $73,000 because the traditional 401(k) deferral remains included. Social Security is ${m('deductions.socialSecurity')} and regular Medicare is ${m('deductions.medicare')}. Additional Medicare does not apply at this wage level.

Subtract the $12,000 of cash deductions and these taxes from gross pay: estimated annual net is ${m('deductions.netAnnual')}. Every allocation below reconciles to the original $75,000. No state or local tax, other payroll deduction or tax credit is modeled.`,sources:['irs2026','ssa','medicare','cafeteria'],exhibits:['gross']},
{id:'deduction-effect',heading:'A contribution is not the same as its tax saving',body:`In the dated example above, the retirement contribution moves money into retirement savings. The reduction in income tax is only one effect of that transfer; it is not an additional contribution and does not mean the transfer has no cash-flow cost. The health deduction buys a benefit under the assumed plan treatment rather than creating spendable income.

Comparing two net estimates can help isolate the current cash-flow effect, provided all other assumptions remain fixed. It does not value the full benefit package, employer contributions, future taxes or investment growth. Those questions require a broader comparison than current take-home pay.

The same distinction carries into a budget. If take-home receipts are used as income, payroll deductions have already been removed. Subtracting the same retirement deferral again from that take-home amount would count it twice. A broader savings-rate measure can include it separately with a clearly chosen denominator.`},
{id:'withholding',heading:'Annual liability is not paycheck withholding',body:`Employers withhold income tax using payroll information and employee elections. Annual liability depends on the tax return’s income, deductions, credits and filing situation. The two amounts need not match. MoneyBasis estimates annual liability within its limited wage-only scope; it does not reproduce W-4 withholding.

Additional Medicare illustrates the difference: employer withholding uses an employee wage trigger independent of the married-joint annual liability threshold. A payroll deduction can therefore appear even when final household liability differs, or final liability can differ because the model lacks other income. The IRS source explains the distinction.`,sources:['medicare']},
{id:'budget-use',heading:'Use a consistent income basis in the monthly plan',body:`For spending decisions, take-home cash is the amount that actually arrives after deductions. Irregular bonuses and varying payroll deductions can make an annual average different from a normal month. Matching deposits and bill dates adds information that a yearly estimate cannot provide.

MoneyBasis’s salary estimate covers one worker, federal ordinary-wage income tax, employee FICA and the base standard deduction for a supported year. It excludes state/local taxes, spouse wages, credits, itemized deductions, additional age-related adjustments, self-employment and special tax treatments. Actual take-home pay can differ for any of those reasons.

The budget planner accepts the monthly income entered; it does not infer which payroll deductions have already occurred. Labeling the input as actual take-home, annualized estimated net or another explicitly defined measure prevents mismatched comparisons later.`},
],exercise:'Set Salary Calculator to $75,000, single, 2026, with a $10,000 traditional 401(k) contribution and $2,000 qualifying health deduction. Reconcile deductions plus federal tax plus Social Security plus Medicare plus estimated net to gross. Use actual take-home receipts when building a cash budget that needs to match real bill dates.',
},
{
slug:'monthly-budget',title:'How to Build a Monthly Budget',seoTitle:'How to Build a Monthly Budget and Track Cash Flow',description:'Build a monthly cash-flow plan from take-home income, regular bills, irregular costs and savings transfers without confusing remaining cash with savings.',summary:'Give income, spending, savings transfers and unassigned cash distinct jobs.',intro:'A monthly budget describes where incoming cash is expected to go. Its value is in making commitments visible, including the costs that do not arrive every month.',takeaway:'Remaining cash flow equals income minus all entered outflows. If a savings transfer is entered as an outflow, it has already been assigned; the remaining balance is additional unassigned cash, not automatically savings.',category:'Income & Budgeting',relatedCalculator:'budget',calculatorAssociations:['budget','savings-goal','debt-snowball'],reviewedAt:'2026-09-18',relatedGuides:['savings-rate-vs-cash-flow','how-much-to-save','gross-vs-net-pay'],ogHeadline:'Where does this month’s money go?',ogSubheadline:'Bills, savings transfers and the cash left unassigned.',fixtureIds:['budget-0','budget-500'],
sections:[
{id:'income-basis',heading:'Start with income that matches the plan',body:`Take-home income is a useful basis for a cash budget because payroll deductions have already been removed. Mixing gross salary with expenses paid from a bank account can make more cash appear available than actually arrives. When an annual salary estimate is divided by twelve, label it as an average rather than the exact amount received each month.

For irregular income, a single month may not be representative. One way to inspect the plan is to compare a lower-receipt month, a more typical month drawn from actual records and a higher-receipt month, without pretending any one is certain. The calculator accepts the scenario entered; it does not forecast variable income.

A cash-flow budget also needs timing. CFPB’s cash-flow tool tracks when money comes in and when it goes out. A positive monthly total can still hide a shortfall before a bill is due if the month’s income arrives later.`,sources:['budget']},
{id:'outflows',heading:'List commitments, including the irregular ones',body:`Recurring expenses include items such as housing, food, transportation, utilities and insurance. Debt payments also consume monthly cash. Savings transfers are cash assignments too, even though moving money between accounts owned by the same person is not consumption.

An annual $600 bill corresponds to $50 per month when spread across twelve months. Setting aside a monthly amount for a known later expense is often called a sinking fund. That conversion makes the annual commitment visible, but an imminent bill may require more than one month’s set-aside if nothing has yet accumulated.

Consistency prevents double-counting. If a credit-card purchase is already counted in its spending category, counting the full later card payment again as new consumption duplicates the purchase. A debt-repayment plan for prior balances is a different cash commitment. Similarly, a savings transfer counted this month should not also be described as cash still available to assign.`},
{id:'example',heading:'Worked example: assign $500 of the remainder',body:`Start with $5,000 of monthly take-home income. Enter $1,500 of housing and $2,200 of other expenses, totaling $3,700. Remaining cash flow is $1,300, and the remaining-income rate is $1,300 ÷ $5,000 = 26%.

Now add a $500 explicit savings transfer as an outflow. Entered outflows become $4,200 and unassigned cash falls to $800. The remaining-income rate becomes 16%. The actual planned savings transfer is 10% of take-home income: $500 ÷ $5,000.

These percentages describe different amounts. The first $1,300 was room left in the entered plan; it was not evidence that $1,300 had been transferred to savings. After the explicit transfer, the $800 remainder can still be assigned, retained as working cash or absorbed by costs missing from the plan.`,exhibits:['budget']},
{id:'deficits-and-zero',heading:'Negative cash flow and zero income are informative states',body:`When entered outflows exceed income, remaining cash flow is negative. For example, $5,500 of outflows against $5,000 of income leaves a $500 deficit. It describes a funding gap in that month’s plan. It does not identify whether the gap is covered by existing cash, new borrowing, delayed payments or an input error.

When income is zero, the remaining dollar amount can still be calculated. With $100 of outflows it is −$100. But remaining cash divided by zero income is undefined, so MoneyBasis leaves the remaining-income rate unavailable rather than showing 0%. A zero-percent rate would incorrectly suggest a valid ratio.

Existing savings can fund a month with little or no income, but drawing down an asset is different from earning new income. A budget can show those movements only if the chosen input basis and categories describe them consistently.`},
{id:'transfers-and-timing',heading:'Separate monthly averages from the bill calendar',body:`A monthly average helps compare ongoing commitments with average income. The bill calendar helps identify which dates need cash. Insurance, tuition, repairs and holiday spending can be lumpy even when their annual average is manageable. A sinking-fund balance is an asset accumulated for those later outflows.

Transfers between your own accounts may appear as withdrawals and deposits on separate bank statements. Adding both as income and expense can inflate activity without changing the household’s position. A consolidated budget can treat the transfer as an assignment while keeping it distinct from a purchase.

The same logic applies to debt principal. It is an outflow from current cash and a reduction in a liability. A cash budget tracks the payment; a net-worth statement shows its balance-sheet effect. Neither view replaces the other.`},
{id:'reviewing',heading:'Use the result to ask specific questions',body:`A category breakdown can show where entered dollars go, but it cannot decide what spending is acceptable. The useful questions are concrete: is a known annual bill missing, has a payroll deduction been counted twice, does an intended transfer fit, and will cash arrive before the next due date?

The calculator does not connect to bank accounts, verify transactions or turn a planned transfer into an actual one. Categories are editable descriptions, not accounting judgments. Comparing the plan with actual records over time can reveal omitted or mistimed amounts.

A budget also is not a savings goal calculation. The goal tool solves for an amount needed under a target and deadline; the budget tests whether that commitment fits the entered cash flow. Their results are connected by an explicit transfer, not by labeling every remaining dollar as saved.`},
],exercise:'Enter $5,000 income, $1,500 housing and $2,200 other expenses. Confirm $1,300 remaining. Add a $500 savings category and confirm $800 remaining with a 16% remaining-income rate. Compare that with the separate 10% savings-transfer rate, then add your irregular costs on a consistent monthly basis.',
},
{
slug:'savings-rate-vs-cash-flow',title:'Savings Rate vs Remaining Cash Flow',seoTitle:'Savings Rate vs Remaining Cash Flow',description:'Distinguish unassigned cash from savings transfers and compare take-home, gross-income and employer-inclusive savings-rate definitions.',summary:'A percentage is only meaningful when its numerator and income basis are named.',intro:'Money left after entered expenses is not proof that money was saved. A useful savings rate identifies an actual or planned savings amount and states exactly which income measure it uses.',takeaway:'MoneyBasis’s budget percentage measures remaining cash divided by entered income. A savings-transfer rate uses explicitly identified savings instead; the two percentages can move in opposite directions.',category:'Income & Budgeting',relatedCalculator:'budget',calculatorAssociations:['budget','savings-goal','retirement'],reviewedAt:'2026-09-18',relatedGuides:['monthly-budget','gross-vs-net-pay','how-much-to-save'],ogHeadline:'Unassigned cash is not yet savings',ogSubheadline:'Reconcile the dollars before comparing the percentages.',fixtureIds:['budget-0','budget-500'],
sections:[
{id:'define-the-measures',heading:'Define the dollars before naming the rate',body:`Income is the inflow measured over a chosen period. Entered expenses and other outflows are amounts assigned away from that inflow. Remaining cash is the difference. A savings transfer is a specific assignment to savings, whether it has already occurred or is still a plan.

MoneyBasis’s budget engine subtracts every entered category, including a category named Savings, from income. It then divides the remainder by income to obtain the remaining-income rate. It does not infer that the remainder has been deposited, invested or retained through the end of the month.

A cash-flow plan also differs from an account reconciliation. The former describes expected movements; the latter checks actual ones. Labeling a transfer as planned or completed avoids implying that a budget entry by itself increased an account balance.`,sources:['budget']},
{id:'example',heading:'The same $5,000 income can tell different stories',body:`With $3,700 in expenses and no entered savings transfer, $5,000 of take-home income leaves $1,300 unassigned. That is a 26% remaining-income rate. If no saving occurred, an actual savings-transfer rate for that month could be zero; the remainder alone does not establish otherwise.

Add a planned $500 savings transfer. Total entered outflows become $4,200 and remaining cash becomes $800, or 16% of take-home income. The planned savings-transfer rate is 10%. The lower remaining-income rate does not mean the plan is saving less: some previously unassigned cash now has an explicit destination.

If the $800 is later also transferred and retained, total transfers would be $1,300 for a 26% transfer rate on this take-home basis. That is an additional observed or planned action, not a conclusion supplied by the original budget result.`,exhibits:['budget']},
{id:'denominators',heading:'Gross and take-home denominators answer different questions',body:`A rate of $500 divided by $5,000 measures after-payroll savings transfers relative to take-home cash. It leaves out retirement contributions withheld before that cash arrived. A broader measure can include those contributions, but needs a consistent income denominator.

Consider a separate illustrative compensation scenario: $8,000 gross monthly pay, a $400 employee retirement contribution, $500 saved from take-home pay and a $200 employer contribution. Employee-only saving is $900; divided by gross pay it is 11.25%. If employer contributions are included in both saving and compensation, $1,100 divided by $8,200 is about 13.41%.

These are explicitly chosen definitions, not a universal personal-finance standard. Dividing the employer-inclusive numerator by $8,000 instead would answer another defined question. Comparisons between people or periods need the same treatment of compensation, transfers and denominators to be meaningful.`,exhibits:['savings-rate'],sources:['retirementTax']},
{id:'transfers-versus-growth',heading:'Keep investment growth out of a transfer measure',body:`A rising account balance can reflect deposits, market changes, credited interest or transfers from another account. Only looking at the ending balance mixes those causes. An explicit savings-transfer measure counts contributions under its chosen definition rather than treating an unrealized market gain as saving out of current income.

Moving existing money between two accounts is not automatically new household saving. A sinking-fund transfer for a future annual bill can be valuable cash planning, but its later spending changes how much remains accumulated over a longer period. Counting gross deposits without considering withdrawals can overstate retained savings.

Debt principal payments also improve a balance sheet by reducing liabilities. Some broader measures include debt reduction; the transfer rate used here does not silently do so. A metric can be useful with either scope when its definition stays visible.`},
{id:'zero-and-deficit',heading:'A cash-flow percentage can be negative or unavailable',body:`A negative remainder indicates outflows above income. It is possible to transfer money to savings during such a month while drawing down another account or borrowing elsewhere. A positive transfer rate alone would then omit the broader funding shortfall.

With zero income, dividing by income is undefined. MoneyBasis still displays the remaining dollar amount but does not invent a zero remaining-income rate. A savings ratio with a zero denominator likewise needs to remain unavailable.

Employer contributions, payroll deferrals, take-home transfers and unassigned cash belong in a reconciliation with distinct labels. None of these measures supplies a universal target or a verdict about a household. Their purpose is to make the underlying movements understandable enough to connect a budget, a specific savings goal and a retirement contribution plan.`},
],exercise:'Use the $5,000 budget example and add or remove the $500 savings transfer. Watch remaining cash change, then calculate the transfer rate separately with the same take-home denominator. If including payroll or employer retirement contributions in a broader measure, write down both the numerator and the compensation denominator before comparing percentages.',
},
];
