import type { GuideContent } from '../types';
export const netWorthGuide: GuideContent = {
slug:'net-worth',title:'How to Calculate Your Net Worth',seoTitle:'How to Calculate Your Net Worth',description:'Build a dated assets-minus-liabilities snapshot, keep full property value separate from mortgage debt and distinguish net worth from spendable cash.',summary:'List what you own and owe without counting home equity twice.',intro:'Net worth is a balance-sheet snapshot: the value of assets minus the liabilities owed on the same date. It becomes more useful when the values, ownership scope and liquidity remain visible.',takeaway:'Include the full value of an owned home as an asset and its mortgage as a separate liability. Entering only home equity and then subtracting the mortgage again counts the debt twice.',category:'Financial Basics',relatedCalculator:'net-worth',calculatorAssociations:['net-worth','budget','rent-vs-buy'],reviewedAt:'2026-09-18',relatedGuides:['monthly-budget','rent-vs-buy-costs','compound-interest'],ogHeadline:'What you own, minus what you owe',ogSubheadline:'A dated snapshot with assets and liabilities kept separate.',fixtureIds:['net-worth'],
sections:[
{id:'snapshot',heading:'Choose a date and a consistent ownership scope',body:`Net worth = total assets − total liabilities. Investor.gov’s balance-sheet approach begins with that inventory. Both sides need to describe the same person or household and the same valuation date. Comparing a current mortgage balance with a property value from many years earlier can obscure what the result means.

For a household statement, jointly owned assets and debts can be included once at their full household amounts. For an individual statement, use a consistent ownership share and document how associated obligations are allocated. A percentage share of an asset does not by itself settle legal responsibility for a joint debt.

The resulting number is a summary, not a credit score or a judgment. A negative value simply means entered liabilities exceed entered assets on that date. Its interpretation depends on the asset mix, income, repayment obligations and circumstances that the single number cannot express.`,sources:['netWorth']},
{id:'inventory',heading:'Inventory assets and liabilities separately',body:`Assets can include cash, bank balances, investments, retirement accounts, property, vehicles and other items with a reasonably supportable value. Use a valuation method that matches the purpose of the snapshot. A vehicle’s original purchase price, an insurance replacement amount and a plausible resale value are different measures.

Liabilities include mortgage balances, credit-card debt, student loans, auto loans, personal loans and other obligations. A balance owed is not the same as its monthly payment. Substituting a payment for a debt balance dramatically understates the liability.

Cash and quoted investments can often be valued directly from statements, while property and other assets require estimates. Recording the source and date makes it easier to distinguish a real change from a revised estimate when the snapshot is updated.`},
{id:'example',heading:'Worked example: full home value, separate mortgage',body:`On one valuation date, list $12,000 of cash, $45,000 of investments and a home valued at $300,000. Total assets are $357,000. With a separate $240,000 mortgage liability and no other entered debt, net worth is $117,000.

The home contributes $60,000 of equity to that total: $300,000 minus $240,000. The other $57,000 comes from cash and investments. The visual shows assets and liabilities on the same scale, with the difference reported as net worth.

If only $60,000 of home equity were entered as the property asset and the $240,000 mortgage were still listed as a liability, the home’s contribution would incorrectly become −$180,000. The full-value method avoids this double subtraction. An equity-only method would have to omit the matching mortgage, but mixing the two methods is the error.`,exhibits:['net-worth']},
{id:'liquidity',heading:'Net worth is not a cash balance',body:`Cash is readily available for spending. Home equity and other illiquid assets can require time, a sale or new borrowing to access. Retirement assets may have access restrictions and tax consequences. Two households with the same net worth can therefore have very different amounts available for an immediate bill.

The snapshot uses entered values before any unmodeled selling expenses or taxes. It is not necessarily the cash that would remain if every asset were liquidated. Valuation uncertainty can also be much greater for a property or private asset than for a checking account.

A monthly budget answers how current inflows meet outflows. Net worth answers what assets remain after liabilities at one moment. A strong result in one view does not automatically resolve a shortfall in the other.`},
{id:'projection',heading:'Keep an illustrative projection separate from today’s arithmetic',body:`The current snapshot is subtraction. MoneyBasis’s optional future view is an illustrative projection under selected assumptions. It applies one asset-return rate to the aggregate assets and one debt-interest rate to aggregate liabilities, with monthly savings and debt-paydown amounts funded from outside the modeled balance sheet.

That is a deliberately simplified structure. A house, cash account and retirement portfolio do not necessarily earn the same return. A mortgage and credit card do not necessarily have the same interest rate. Combining them under one rate can be useful for a broad scenario but is not a security-by-security forecast or a loan-by-loan schedule.

Monthly contributions arrive after growth. Debt payments are capped at the balance plus interest, and unused debt-paydown money is redirected into assets after debt is cleared. With all rates and contributions set to zero, the worked example stays at $117,000; that control keeps the projection from being mistaken for extra wealth already owned.`},
{id:'update',heading:'Explain changes before interpreting them',body:`A later snapshot can change through new saving, investment gains or losses, debt reduction, spending from assets, borrowing or a different valuation estimate. A higher balance is not automatically evidence of a higher savings rate. A transfer between owned accounts can change the category totals without changing net worth at all.

Using the same scope and valuation method makes snapshots more comparable. If the method changes, note the change alongside the amount. The calculator cannot verify ownership, market value or the completeness of the inventory; it accurately summarizes the numbers entered within its stated model.

A useful reading of the result therefore keeps three things together: the net amount, the assets and debts that produced it, and the amount that is actually liquid. That combination reveals more than the headline alone.`},
],exercise:'Enter assets of $357,000 and debts of $240,000 to reproduce the $117,000 snapshot. In the optional projection, set growth, debt interest, monthly savings and debt paydown to zero; all future snapshots then remain equal to the current value. Then change one projection assumption at a time while keeping the current snapshot distinct from the future scenario.',
};
