import type { GuideContent } from '../types';
import { money as m } from '../numbers';
export const retirementGuide: GuideContent = {
slug:'four-percent-rule',title:'The 4% Rule: Origins, Inflation and Retirement Risk',seoTitle:'The 4% Rule: Origins, Inflation and Retirement Risk',description:'Understand initial withdrawals, inflation adjustments, Bengen and Trinity research, sequence risk and the limits of a deterministic retirement calculator.',summary:'Separate first-year arithmetic from a withdrawal policy and the risk of running out.',intro:'Multiplying a portfolio by 4% is easy. Deciding what that amount means over a retirement requires a withdrawal policy, a time horizon and an understanding of what historical evidence can—and cannot—establish.',takeaway:'The familiar policy starts with a percentage of the original portfolio, then adjusts that dollar withdrawal for inflation. It is different from withdrawing the same percentage of the current balance each year, and neither is a promise of an adequate lifelong income.',category:'Retirement',relatedCalculator:'retirement',calculatorAssociations:['retirement','compound-interest','budget'],reviewedAt:'2026-09-18',relatedGuides:['nominal-vs-real-return','compound-interest','savings-rate-vs-cash-flow'],ogHeadline:'What the 4% rule actually describes',ogSubheadline:'An initial withdrawal, inflation and an uncertain path.',fixtureIds:['retirement'],
sections:[
{id:'first-year',heading:'Start with the first-year arithmetic',body:`A withdrawal rate expresses an annual withdrawal as a percentage of a defined portfolio balance. With $750,000 at retirement, 4% is $30,000 in the first year, or a $2,500 monthly equivalent. The multiplication alone does not say whether the portfolio will support that spending for ten years, thirty years or longer.

The denominator is important: in the familiar initial-percentage policy, it is the original retirement portfolio. A different starting balance changes the dollar withdrawal even if the percentage stays the same. A different percentage changes the initial spending amount without changing the portfolio itself.

The table includes 3%, 4% and 5% to show that arithmetic. These are illustrative choices, not recommendations or estimates of the probability of success. Taxes and fees have not been deducted from the displayed withdrawals.`,exhibits:['retirement-rates']},
{id:'origins',heading:'Bengen in 1994; the Trinity study in 1998',body:`William P. Bengen’s October 1994 paper examined historical U.S. stock and intermediate-term Treasury returns alongside inflation. It studied portfolio longevity with an initial withdrawal followed by inflation adjustments, giving the 4% starting figure its influential historical foundation for a roughly thirty-year horizon. Its conclusions depended on the tested asset mixes and periods.

The 1998 study by Philip L. Cooley, Carl M. Hubbard and Daniel T. Walz, commonly called the Trinity study, examined historical stock/bond portfolios across multiple withdrawal rates and payout periods of fifteen to thirty years. It included inflation-adjusted withdrawals and reported outcomes across historical periods. Taxes and transaction costs were excluded.

These were related historical investigations, not the same paper. A frequency of success in overlapping past periods is not a guaranteed outcome or a calibrated probability for a new retiree.`,sources:['bengen','bengenText','trinity']},
{id:'example',heading:'Policy A: fix the initial percentage, then adjust the dollars',body:`Take the $750,000 portfolio and an initial $30,000 annual withdrawal. With a constant 3% inflation assumption, the second-year amount is $30,900 and the third-year amount is $31,827. Each new amount is the prior dollar withdrawal multiplied by 1.03.

The policy does not recompute 4% of the portfolio each year. Spending rises with the assumed price level even if the portfolio falls. Consequently, a later withdrawal can represent a much larger percentage of the remaining assets than the initial 4%.

The timeline below is a spending rule only. It does not contain investment returns or calculate a terminal portfolio balance. Its tenth-year number describes the spending requested by the policy, not proof that the portfolio can supply it. The constant inflation rate is a teaching assumption; real inflation varies.`,exhibits:['retirement']},
{id:'current-percentage',heading:'Policy B: take a percentage of the current portfolio',body:`A current-balance policy instead recalculates the withdrawal from the portfolio measured at each withdrawal date. At 4%, a current balance of $600,000 produces $24,000; a current balance of $900,000 produces $36,000. Those amounts do not come from inflating the original $30,000.

This makes withdrawals responsive to the portfolio, but it shifts uncertainty into spending. The amount available after a decline can be insufficient for expenses. In a simplified model, taking a fraction smaller than the entire positive balance avoids mechanically emptying it in one withdrawal, yet that observation does not establish an adequate income or protection from extreme losses and costs.

Neither policy is a description of every real retirement plan. Rules can include spending floors, caps or adjustments after market changes. Those additional policies need their own explicit definitions and tests; combining features informally can produce a plan that matches neither the initial-percentage research nor a current-balance calculation.`},
{id:'sequence-risk',heading:'The order of returns matters when money leaves',body:`Consider a separate, invented two-year example with $100,000 initially and a $10,000 withdrawal at each year end, after that year’s investment return. There is no inflation, fee or tax adjustment. One path returns +20% and then −20%; the other has the same returns in reverse order.

In the first path, $100,000 grows to $120,000 and the withdrawal leaves $110,000. A 20% loss then reduces it to $88,000; the second withdrawal leaves $78,000. In the reverse path, the first loss leaves $80,000 and the withdrawal reduces it to $70,000. A subsequent 20% gain brings it to $84,000; the next withdrawal leaves $74,000.

Without withdrawals, both paths end at $96,000 because 1.2 × 0.8 equals 0.8 × 1.2. With withdrawals, their ending balances differ by $4,000. Earlier losses leave fewer dollars participating in the later recovery after cash has been removed. This is a compact demonstration of sequence risk.

The example is independent arithmetic, not Bengen or Trinity data, a Monte Carlo simulation, or a test of the 4% policy. Its deliberately large annual returns and fixed withdrawals isolate the mechanism. Changing withdrawal timing or amounts changes the outcome.`,exhibits:['sequence']},
{id:'allocation-and-horizon',heading:'Asset mix and horizon belong in the question',body:`A retirement horizon states how long a portfolio is asked to support withdrawals. Extending the horizon adds payments and exposure to future market and price changes. Finishing one selected period with assets remaining cannot establish that the same spending can continue indefinitely.

Asset allocation affects the return path and risk of the portfolio supplying those payments. A constant-return calculator does not specify a stock/bond mix or model rebalancing, correlations or market drawdowns. Entering one annual return cannot reproduce the many assumptions behind a historical portfolio study.

Inflation interacts with both. A spending policy tied to prices can demand more nominal dollars during periods when the investment portfolio is already under pressure. A high long-run average return is not sufficient evidence that each earlier withdrawal can be funded along the way.`},
{id:'tax-fees-and-flexibility',heading:'Spendable income also depends on taxes, costs and flexibility',body:`A gross portfolio withdrawal is not necessarily the amount available for living costs. Tax treatment depends on the accounts and circumstances. Investment and advisory costs also remove money from the portfolio. An example that excludes them cannot be interpreted as an after-tax, after-fee spending promise.`,sources:['fees']},
{id:'other-income',heading:'Keep other income and spending changes explicit',body:`Social Security and pension payments are separate from portfolio withdrawals. A retirement budget can identify the portion of spending those sources are expected to fund and the remaining portion requested from investments, with consistent tax and dollar-date assumptions. Social Security’s own planning tools provide personal benefit estimates; MoneyBasis does not calculate them.

Spending flexibility can change the cash requested from a portfolio, but reducing a modeled withdrawal is not the same as proving a household can reduce real expenses. Essential commitments, discretionary spending and one-time costs can behave differently. A constant spending path does not represent all of them.

MoneyBasis’s desired-spending input drives portfolio withdrawals. If the entered amount represents only a gap after separately estimated benefits, record that choice. Entering total spending while also assuming unmodeled benefits are automatically added would misread the output.`,sources:['socialSecurityPlanning']},
{id:'moneybasis-model',heading:'What the MoneyBasis retirement calculator actually does',body:`During accumulation, savings grow at the entered nominal annual rate divided by twelve and receive contributions at month end. The projected nest egg is expressed in future nominal dollars. The selected withdrawal percentage is applied to that nest egg to produce an initial annual and monthly withdrawal estimate.

Desired monthly spending is entered in today’s dollars. The calculator inflates it to retirement, then increases the nominal spending amount annually during the drawdown period. That requested spending drives the drawdown, independently of the selected withdrawal-rate headline. Changing only the selected percentage changes the initial-rate estimate; it does not silently rewrite the desired-spending policy.

For example, age 30 to 65, $25,000 currently saved, $800 contributed monthly, 7% nominal annual return, no contribution increases, 3% inflation and $4,000 of monthly spending in today’s dollars produce a projected nest egg of ${m('retirement.nest')}. The initial 4% monthly equivalent is ${m('retirement.monthly')}, while desired monthly spending at retirement is ${m('retirement.need')}. The inflation adjustment is essential to that comparison.

During drawdown, the model uses the lower of the entered nominal annual return and 5%, divided by twelve. This is an explicit planning cap, not a risk guarantee or a historical-study assumption. It does not simulate varying returns, asset allocation or sequence risk. Taxes, fees, Social Security and pensions are not added automatically.`},
{id:'reading-status',heading:'Read a finite projection as a finite projection',body:`A funded-through-horizon result means the deterministic schedule retains money through the selected ending age. It does not mean the funds never run out. A depleted result records exhaustion within that modeled period under the entered spending and growth assumptions.

The sequence illustration above explains a risk that this smooth model cannot measure. Changing the constant return or spending can show sensitivity, but the resulting curves do not become probabilities of survival. The tool answers what follows from one set of inputs, while historical research asks what happened across specified past paths.

Keeping these questions separate preserves the useful role of each: initial-rate arithmetic for scale, spending projections for a defined scenario, and historical or other risk analysis for uncertainty that a single deterministic path omits.`},
],exercise:'Enter age 30, retirement at 65, ending age 90, $25,000 saved, $800 monthly contributions, 0% contribution increase, 7% annual return, 3% inflation, $4,000 desired monthly spending in today’s dollars and a 4% withdrawal rate. Compare the initial-rate estimate with inflated desired spending. Change only the withdrawal rate, then separately change desired spending and observe which result each controls.',
};
